### ISSUE TITLE
卡在命令行了

### ISSUE THREAD

**Issue by skyeKing** [Weizhi-Zhong/IP_LAP#13]
生成完毕后，命令行里没有结束提醒
![微信图片_20230608195714](https://github.com/Weizhi-Zhong/IP_LAP/assets/17171471/99d8a004-a9ca-4038-95f5-ccb777be4af7)

一直卡在这儿

**Comment by Weizhi-Zhong** [comment]
Hi, thanks for your interest. 
It seems that the problem may exist in the ffmpeg tool.
maybe you can try `conda install ffmpeg`.
Or you can use the print command to debug and find where the program is stuck.

**Comment by Weizhi-Zhong** [comment]
> Thank you very much
