### ISSUE TITLE
怎么让最终的视频只输出右侧的而不输出左侧的

### ISSUE THREAD

**Issue by skyeKing** [Weizhi-Zhong/IP_LAP#14]
如题

**Comment by Weizhi-Zhong** [comment]
Hi， thanks for your interest.
modify the following two lines:

https://github.com/Weizhi-Zhong/IP_LAP/blob/853f35df6b5ea8c9bee335effd8e9cef1457a978/inference_single.py#LL511C1-L511C55

https://github.com/Weizhi-Zhong/IP_LAP/blob/853f35df6b5ea8c9bee335effd8e9cef1457a978/inference_single.py#LL420C1-L421C67
