### ISSUE TITLE
LRS2不能商用诶

### ISSUE THREAD

**Issue by skyeKing** [Weizhi-Zhong/IP_LAP#16]
中文的可以替换[LRS2](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html)方案的思路有没有诶

**Comment by Weizhi-Zhong** [comment]
Hi, thanks for your interest.
Sorry, all datasets I know of are in English.

Maybe you could collect your dataset based on your needs, e.g., from [CCTV ](https://tv.cctv.com/) or others.

**Comment by wangdezhong** [comment]
> 中文的可以替换[LRS2](https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html)方案的思路有没有诶

https://www.vipazoo.cn/CMLR.html   这是我找到的中文数据集 你可以试试看
