### ISSUE TITLE
The talking head speaks at silence parts

### ISSUE THREAD

**Issue by KingStorm** [Weizhi-Zhong/IP_LAP#18]
Hi, 

it's me again.

I have successfully train a talking head using your repo.

However, I noticed there are some bad cases: when the audio is actually silent, the lips of talking head still move and open mouth.

Any insights about this? thanks. 

Setup:
- dataset used for training: 30 hours

**Comment by Weizhi-Zhong** [comment]
Hi, thanks for your interset 
maybe you can refer to this [issue](https://github.com/Weizhi-Zhong/IP_LAP/issues/5#issuecomment-1554117978)

**Comment by KingStorm** [comment]
Thanks.
