### ISSUE TITLE
AttributeError: _2D

### ISSUE THREAD

**Issue by Inferencer** [Weizhi-Zhong/IP_LAP#19]
Hello I recently installed with no issues but when I run the test on windows annaconda I get the following

```
(iplip) C:\Users\leolo\IP_LAP>python inference_single.py
Traceback (most recent call last):
  File "inference_single.py", line 34, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False, device='cuda')
  File "C:\Users\leolo\anaconda3\envs\iplip\lib\enum.py", line 354, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
```

All my versions seems correct according to the repo and the requirments.txt, the only thing i am doing differently is using 
`python inference_single.py`
as when i use
`CUDA_VISIBLE_DEVICES=0 python inference_single.py`
i get the following error 
```
(iplip) C:\Users\leolo\IP_LAP>CUDA_VISIBLE_DEVICES=0 python inference_single.py
'CUDA_VISIBLE_DEVICES' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by huangxin168** [comment]
change to face-alignment==1.3.4 solve this

**Comment by Inferencer** [comment]
fixed thankyou

**Comment by MYTHOFLEGEND** [comment]
change face_alignment.LandmarksType._2D to face_alignment.LandmarksType.TWO_D
