### ISSUE TITLE
训练video renderer的时候进度条卡住

### ISSUE THREAD

**Issue by nq239** [Weizhi-Zhong/IP_LAP#28]
非常感谢作者您为社区带来的开源贡献！我遇到了一个问题，在训练video renderer的时候数据加载完毕之后卡住了，如下图，我只有一个gpu，执行的命令是：python train_video_renderer.py --sketch_root .\output\lrs2_sketch --face_img_root .\output\lrs2_face  --audio_root .\output\lrs2_audio      windows系统
![image](https://github.com/Weizhi-Zhong/IP_LAP/assets/126679829/db0e66a5-aefb-4b12-9c6e-baa2f3f35f4d)

**Comment by nq239** [comment]
这个问题出现在我把num_worker改为8的时候，但是num_worker较大时会出现以下报错
![image](https://github.com/Weizhi-Zhong/IP_LAP/assets/126679829/a9a83c42-c076-4b10-b94b-d4bb7cc983ce)

**Comment by MYTHOFLEGEND** [comment]
我也遇到了这个问题，请问你是怎么解决的啊

**Comment by nq239** [comment]
> 

如果你是windows系统的话，可以检查一下test.txt和train.txt里面的文件分隔符，要改成\
![image](https://github.com/Weizhi-Zhong/IP_LAP/assets/126679829/bafbb6db-fd03-43c0-b123-a0afd42dcec1)

**Comment by MYTHOFLEGEND** [comment]
我用的是linux，而且用的是我自己的训练数据，不是lrs2😂

**Comment by nq239** [comment]
> 我用的是linux，而且用的是我自己的训练数据，不是lrs2😂

那估计是数据没处理好，你可以检查一下视频是不是都有人脸，没有人脸的部分截掉
