### ISSUE TITLE
Slow Training Speed on LRS2 Dataset with 4x RTX 4090 GPUs,(train_video_renderer.py)

### ISSUE THREAD

**Issue by Kiri0824** [Weizhi-Zhong/IP_LAP#41]
I attempted to run train_video_renderer.py on the LRS2 dataset using four RTX 4090 GPUs, but the training speed is exceptionally slow. In a previous issue, I noticed that the author suggested running approximately 300 epochs for optimal results. However, the speed I'm experiencing is much lower than expected. Does anyone has same issue?
![image](https://github.com/Weizhi-Zhong/IP_LAP/assets/82167034/fc812ad7-4d5b-43c1-8187-afcfb3971f85)

**Comment by Kiri0824** [comment]
BTW, #12 , i see the author said: We stop training near 300 epochs, where FID is around 19, eval_gen_loss is around 7, and eval_warp_loss is around 11. ​But this training uses ref_N=3.
Here's my loss:
![image](https://github.com/Weizhi-Zhong/IP_LAP/assets/82167034/ad03383c-7fff-4e95-a560-63ee43e3bdd8)
I didn't train 25 epoch, so others loss didn't decrease. But the eval_warp_loss is a little low, is that normal😢

**Comment by Kiri0824** [comment]
it's normal. i fix it😊

**Comment by paulovasconcellos-hotmart** [comment]
Can you share how you fixed it?

**Comment by Kiri0824** [comment]
sorry for a long time to reply, its just normal, just wait for a few days :)

**Comment by Kiri0824** [comment]
> Can you share how you fixed it?

sorry for a long time to reply, its just normal, just wait for a few days :)
